# docker-compose
version: '3.8'
services:
  client:
    image: client/client-bateau-thibault-dev:latest
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"  #live reload server is 49153 while normal server is 4200 where changes refresh when browser refreshed
      - "49153:49153"
    working_dir: /applis/dev/client/
    volumes:
      - ./client:/applis/dev/client/
      - /applis/dev/client/node_modules