# docker-compose
version: '3.8'
services:
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - server
    expose:
      - "80"
    ports:
      - "8080:80"
    networks:
      - frontend
    working_dir: /applis/prod/client/

  database:
    container_name: postgresql_db
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - backend

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
      ports:
        - "5050:80"
      depends_on:
        - database

  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - .:/applis/prod/server/
    depends_on:
      - database
    ports:
      - "8000"
    networks:
      - frontend
      - backend
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 30s"
      ofelia.job-exec.datecron.command: "python server/run/manage.py sale"
      ofelia.job-exec.productcron.schedule: "@every 60s"
      ofelia.job-exec.productcron.command: "python server/run/manage.py load_products"

  ofelia:
    container_name: ofelia_crontab
    image: mcuadros/ofelia:latest
    command: daemon --docker
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
