# docker-compose
version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"  #live reload server is 49153 while normal server is 4200 where changes refresh when browser refreshed
      - "49153:49153"
    depends_on:
      - server
    working_dir: /applis/dev/client/
    volumes:
      - ./client:/applis/dev/client/
      - /applis/dev/client/node_modules
    networks:
      - frontend
  database:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - database

  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - .:/applis/prod/server/
    depends_on:
      - database
    ports:
      - "8000"
    networks:
      - frontend
      - backend
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 30s"
      ofelia.job-exec.datecron.command: "python server/run/manage.py sale"
      ofelia.job-exec.productcron.schedule: "@every 60s"
      ofelia.job-exec.productcron.command: "python server/run/manage.py load_products"

  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
