
web:
  build: .
  volumes:
    - .:/code
web_migrate:
  extends:
    service: web
  command: bash -c "python run/manage.py makemigrations && python run/manage.py migrate"
web_run:
  extends:
    service: web
  ports:
    - "8000:8000"
  command: bash -c "python run/manage.py runserver 0.0.0.0:8000"
