web:
  build: .
  volumes:
    - .:/code
web_migrate:
  extends:
    service: web
  command: bash -c "python run/manage.py migrate && python run/manage.py load_products && python run/manage.py setup_fake_data"
web_run:
  extends:
    service: web
  ports:
    - "8000:8000"
  command: bash -c "python run/manage.py runserver 0.0.0.0:8000"
