
web:
  build: .
  volumes:
    - .:/code
web_migrate:
  extends:
    service: web
  command: bash -c "python run/manage.py makemigrations && python run/manage.py migrate"
web_run:
  extends:
    service: web
  ports:
    - "8000:8000"
  command: bash -c "python run/manage.py runserver 0.0.0.0:8000"
  labels:
    ofelia.enabled: "true"
    ofelia.job-exec.datecron.schedule: "@every 30s"
    ofelia.job-exec.datecron.command: "python run/manage.py sale"
    ofelia.job-exec.productcron.schedule: "@every 60s"
    ofelia.job-exec.productcron.command: "python run/manage.py load_products"
ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
